#!/usr/bin/env bash

word=${1:-$(xclip -o -selection primary | tr -d '\n')}

#word=$(printf '%s' "${1:-$(wl-paste -p 2>/dev/null || wl-paste 2>/dev/null)}" | tr -d '\n')

#[ -z "$word" ] && notify-send "Nothing selected or copied" && exit 0


encoded_word=$(printf '%s' "$word" | jq -sRr @uri)

query=$(curl -s "https://api.dictionaryapi.dev/api/v2/entries/en_US/$encoded_word") || {
    notify-send -h string:bgcolor:#bf616a -t 3000 "API error"
    exit 1
}

if echo "$query" | jq -e 'type=="object" and .title=="No Definitions Found"' >/dev/null; then
    notify-send -h string:bgcolor:#bf616a -t 3000 "Invalid word."
    exit 0
fi

def=$(echo "$query" | jq -r '
  .[0].meanings[]
  | "\(.partOfSpeech): \(.definitions[0].definition)\n"
')
if [ -z "$def" ];then 
	notify-send -h string:bgcolor:#bf616a -t 3000 "Dictionary" "Try Different word"
	exit 1
fi
notify-send -t 10000 "$word -" "$def"

