#!/usr/bin/env bash

raw=$(salahtime)
declare -A prayertm

ctime=""

while read -r line; do
    # Parse Prayer Times
    if [[ $line =~ ^([A-Za-z]+):[[:space:]]+([0-9]{2}:[0-9]{2}) ]]; then
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"
        prayertm["$key"]=$value

    # Parse Current Time
    # added '.*' to handle the extra non-breaking spaces in your text input
    elif [[ $line =~ Current.*time.*([0-9]{2}:[0-9]{2}) ]]; then
        ctime="${BASH_REMATCH[1]}"
    fi
done <<< "$raw"

order=("Fajr" "Shuruk" "Dhuhr" "Asr" "Maghrib" "Isha")

current_prayer="Isha"

for prayer in "${order[@]}"; do
    prayer_time="${prayertm[$prayer]}"

    # Skip if we couldn't find a time for this prayer key
    if [[ -z "$prayer_time" ]]; then continue; fi

    # Compare Strings
    if [[ "$prayer_time" > "$ctime" ]]; then
       
        break
    fi
    current_prayer="$prayer"
done

echo "$current_prayer"
